definitions:
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    type: object
  model.RegisterRequest:
    properties:
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        minLength: 8
        type: string
      profile:
        type: string
      username:
        type: string
    required:
    - email
    - firstname
    - lastname
    - password
    - username
    type: object
info:
  contact: {}
  description: Authentication Service สำหรับขอจัดการเกี่ยวกับ Authentication
  title: Authentication Service API
  version: v0
paths:
  /auth/login:
    post:
      description: Login user
      operationId: Login
      parameters:
      - description: User data to login
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Login
      tags:
      - Authentications
  /auth/register:
    post:
      description: Register user
      operationId: Register
      parameters:
      - description: User data to create
        in: body
        name: registerRequest
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Register
      tags:
      - Authentications
schemes:
- http
swagger: "2.0"
